### PR TITLE
Upgrade vue-styleguidist dependency

### PR DESCRIPTION
**Pull request by pepesenaris**
Upgrade to latest vue-styleguidist.

This solves an issue in [vue-styleguidist](https://github.com/vue-styleguidist/vue-styleguidist/issues/237#issuecomment-456185410) that prevented using more complex type definitions, for example using something like: https://github.com/dwightjack/vue-types

### CODE REVIEW

**Comment by elevatebart** [comment]
For now, complex types are parsed and do not return an error, 
They are properly ignored by vu-docgen-api. 
I suggest we wait for https://github.com/vue-styleguidist/vue-docgen-api#90 to merge before updating.

**Comment by elevatebart** [comment]
I believe you can now update vsg ;)

**Comment by pepesenaris** [comment]
Updated

**Comment by elevatebart** [comment]
Hello @pepesenaris, I included your PR in this one #206 
I hope you find it to your liking

**Comment by pepesenaris** [comment]
Thanks, keep the great work :muscle:

**Pull request closed without merging**
